In [58]:
import numpy as np
import pandas as pd

In [59]:
train = pd.read_csv('C:\\Users\\HP\\Desktop\\disaster_tweets\\train.csv')

In [60]:
train.shape

(7613, 5)

In [61]:
train_keyword = train.fillna("none")

In [62]:
train_keyword['hashtags'] = train_keyword['text'].str.findall(r"#(\w+)").apply(' '.join)
train_keyword['hashtags'] = np.where(train_keyword['hashtags'] == "", 'no_hashtag', train_keyword['hashtags'])
# train_keyword['hashtags']

In [63]:
# train_keyword['username'] = train_keyword['text'].str.extract(r"(@\w+)")
# train_keyword['username'] = np.where(train_keyword['username'].isna()==False, 1, 0)
# train_keyword['hashtags']

In [64]:
train_keyword

,id,keyword,location,text,target,hashtags
0,1,none,none,Our Deeds are the Reason of this #earthquake M...,1,earthquake
1,4,none,none,Forest fire near La Ronge Sask. Canada,1,no_hashtag
2,5,none,none,All residents asked to 'shelter in place' are ...,1,no_hashtag
3,6,none,none,"13,000 people receive #wildfires evacuation or...",1,wildfires
4,7,none,none,Just got sent this photo from Ruby #Alaska as ...,1,Alaska wildfires
...,...,...,...,...,...,...
7608,10869,none,none,Two giant cranes holding a bridge collapse int...,1,no_hashtag
7609,10870,none,none,@aria_ahrary @TheTawniest The out of control w...,1,no_hashtag
7610,10871,none,none,M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...,1,no_hashtag
7611,10872,none,none,Police investigating after an e-bike collided ...,1,no_hashtag
7612,10873,none,none,The Latest: More Homes Razed by Northern Calif...,1,no_hashtag

In [65]:
import category_encoders as ce

# Target encoding
features = 'keyword'
encoder = ce.TargetEncoder(cols=features)
encoder.fit(train[features],train['target'])

train_keyword['keyword_target'] = encoder.transform(train[features])

# train_keyword['keyword_target']

C:\Users\HP\anaconda3\lib\site-packages\category_encoders\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):

In [66]:
train_keyword

,id,keyword,location,text,target,hashtags,keyword_target
0,1,none,none,Our Deeds are the Reason of this #earthquake M...,1,earthquake,0.688525
1,4,none,none,Forest fire near La Ronge Sask. Canada,1,no_hashtag,0.688525
2,5,none,none,All residents asked to 'shelter in place' are ...,1,no_hashtag,0.688525
3,6,none,none,"13,000 people receive #wildfires evacuation or...",1,wildfires,0.688525
4,7,none,none,Just got sent this photo from Ruby #Alaska as ...,1,Alaska wildfires,0.688525
...,...,...,...,...,...,...,...
7608,10869,none,none,Two giant cranes holding a bridge collapse int...,1,no_hashtag,0.688525
7609,10870,none,none,@aria_ahrary @TheTawniest The out of control w...,1,no_hashtag,0.688525
7610,10871,none,none,M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...,1,no_hashtag,0.688525
7611,10872,none,none,Police investigating after an e-bike collided ...,1,no_hashtag,0.688525
7612,10873,none,none,The Latest: More Homes Razed by Northern Calif...,1,no_hashtag,0.688525

In [67]:
# train['text'].drop_duplicates().shape

In [68]:
train_keyword['cleaned_text'] = train_keyword['text']
train_keyword['cleaned_text'] = train_keyword['cleaned_text'].str.lower()
train_keyword['cleaned_text'] = train_keyword['cleaned_text'].str.replace(r"@\w+", "username")
train_keyword['cleaned_text'] = train_keyword['cleaned_text'].str.replace(r"#\w+", " ")
train_keyword['cleaned_text'] = train_keyword['cleaned_text'].str.replace('http\S+|www.\S+', ' ', case=False)
# train_keyword['cleaned_text'] = train_keyword['cleaned_text'].str.replace(r"[,.]", "")

train_keyword['cleaned_text'] = train_keyword['cleaned_text'].str.replace("[^a-z-'_@]+", " ")
# train_keyword['cleaned_text'] = train_keyword['cleaned_text'].str.replace(r"\d+", "numbers")
train_keyword['cleaned_text'] = train_keyword['cleaned_text'].str.strip()
train_keyword['cleaned_text'] = train_keyword['cleaned_text'].str.replace("\s+", " ")
train_keyword['cleaned_text'] = train_keyword['cleaned_text'].str.split()




# def remove_short_words(text):
#     words = [w for w in text if len(w) > 1]
#     return words

# train_keyword['cleaned_text'] = train_keyword['cleaned_text'].apply(lambda x: remove_short_words(x))



# new_words = ['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 's', 't', 'can', 'will', 'just', 'don', "don't", 'should', "should've", 'now', 'd', 'll', 'm', 'o', 're', 've', 'y', 'ain', 'aren', "aren't", 'couldn', "couldn't", 'didn', "didn't", 'doesn', "doesn't", 'hadn', "hadn't", 'hasn', "hasn't", 'haven', "haven't", 'isn', "isn't", 'ma', 'mightn', "mightn't", 'mustn', "mustn't", 'needn', "needn't", 'shan', "shan't", 'shouldn', "shouldn't", 'wasn', "wasn't", 'weren', "weren't", 'won', "won't", 'wouldn', "wouldn't"]
# def remove_stopwords(text):
#     words = [w for w in text if w not in new_words]
#     return words

# train_keyword['cleaned_text'] = train_keyword['cleaned_text'].apply(lambda x: remove_stopwords(x))


from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

def word_lemmatizer(text):
    lem_text = " ".join([lemmatizer.lemmatize(w) for w in text])
    return lem_text

train_keyword['cleaned_text'] = train_keyword['cleaned_text'].apply(lambda x: word_lemmatizer(x))

train_keyword['cleaned_text'] = train_keyword['cleaned_text'].str.replace("'", "")

In [71]:
train_keyword

,id,keyword,location,text,target,hashtags,keyword_target,cleaned_text
0,1,none,none,Our Deeds are the Reason of this #earthquake M...,1,earthquake,0.688525,our deed are the reason of this may allah forg...
1,4,none,none,Forest fire near La Ronge Sask. Canada,1,no_hashtag,0.688525,forest fire near la ronge sask canada
2,5,none,none,All residents asked to 'shelter in place' are ...,1,no_hashtag,0.688525,all resident asked to shelter in place are bei...
3,6,none,none,"13,000 people receive #wildfires evacuation or...",1,wildfires,0.688525,people receive evacuation order in california
4,7,none,none,Just got sent this photo from Ruby #Alaska as ...,1,Alaska wildfires,0.688525,just got sent this photo from ruby a smoke fro...
...,...,...,...,...,...,...,...,...
7608,10869,none,none,Two giant cranes holding a bridge collapse int...,1,no_hashtag,0.688525,two giant crane holding a bridge collapse into...
7609,10870,none,none,@aria_ahrary @TheTawniest The out of control w...,1,no_hashtag,0.688525,username username the out of control wild fire...
7610,10871,none,none,M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...,1,no_hashtag,0.688525,m utc km s of volcano hawaii
7611,10872,none,none,Police investigating after an e-bike collided ...,1,no_hashtag,0.688525,police investigating after an e-bike collided ...
7612,10873,none,none,The Latest: More Homes Razed by Northern Calif...,1,no_hashtag,0.688525,the latest more home razed by northern califor...

In [70]:
# train_keyword = train_keyword[['cleaned_text', 'target', 'hashtags', 'keyword_target']].drop_duplicates().reset_index(drop = True)

In [72]:
X = train_keyword[['hashtags', 'keyword_target', 'cleaned_text']]
y = train_keyword['target']

In [73]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [74]:
# Parameter selection
ngram_range = (1,2)
min_df = 5
max_df = 0.5

In [76]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(ngram_range=ngram_range, min_df = min_df, max_df = max_df)
                        
X_train_tfidf = tfidf.fit_transform(X_train['cleaned_text'])
X_test_tfidf = tfidf.transform(X_test['cleaned_text'])
# labels_train = y
print(X_train_tfidf.shape)
print(X_test_tfidf.shape)

(6090, 3890)
(1523, 3890)

In [77]:
X_train_tfidf_df = pd.DataFrame(X_train_tfidf.toarray(), columns=tfidf.get_feature_names())
X_test_tfidf_df = pd.DataFrame(X_test_tfidf.toarray(), columns=tfidf.get_feature_names())

In [81]:
from sklearn.feature_extraction.text import CountVectorizer

countvec = CountVectorizer()
X_train_countvec = countvec.fit_transform(X_train['hashtags'])
X_test_countvec = countvec.transform(X_test['hashtags'])

print(X_train_countvec.shape)
print(X_test_countvec.shape)

(6090, 1653)
(1523, 1653)

In [82]:
X_train_countvec_df = pd.DataFrame(X_train_countvec.toarray(), columns=countvec.get_feature_names())
X_test_countvec_df = pd.DataFrame(X_test_countvec.toarray(), columns=countvec.get_feature_names())

In [91]:
X_train_all_features = X_train[['keyword_target']].reset_index(drop = True).merge(X_train_tfidf_df, left_index = True, right_index = True).merge(X_train_countvec_df, left_index = True, right_index = True)
X_test_all_features = X_test[['keyword_target']].reset_index(drop = True).merge(X_test_tfidf_df, left_index = True, right_index = True).merge(X_test_countvec_df, left_index = True, right_index = True)

In [23]:
# from sklearn.preprocessing import MinMaxScaler
# scaler = MinMaxScaler()
# df_scaled = pd.DataFrame(scaler.fit_transform(X),columns = X.columns)

In [103]:
from sklearn.linear_model import LogisticRegression

logistic_reg = LogisticRegression()
logistic_reg.fit(X_train_all_features, y_train)

LogisticRegression()

In [106]:
from sklearn.metrics import accuracy_score

log_pred = logistic_reg.predict(X_test_all_features)
accuracy = accuracy_score(y_test, log_pred)*100
print(format(accuracy, '.2f'))

80.43

In [107]:
from sklearn.metrics import accuracy_score

log_pred_train = logistic_reg.predict(X_train_all_features)
accuracy = accuracy_score(y_train, log_pred_train)*100
print(format(accuracy, '.2f'))

86.88

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score


logistic_reg = LogisticRegression()
cv_score_logistic = cross_val_score(logistic_reg, X_train_all_features, y_train, scoring='accuracy', cv=5, n_jobs=-1)
cv_score_logistic.mean()

In [120]:
error_test = X_test.reset_index().merge(y_test.reset_index(drop = True), left_index = True, right_index = True).merge(pd.DataFrame(log_pred), left_index = True, right_index = True)

In [121]:
error_test

,index,hashtags,keyword_target,cleaned_text,target,0
0,311,no_hashtag,0.119048,username you already know how this shit go wor...,0,0
1,4970,140,0.151515,username username people near meltdown comic w...,0,0
2,527,no_hashtag,0.133333,- tix calgary flame v col avalanche preseason ...,0,0
3,6362,no_hashtag,0.914286,if you ever think you running out of choice in...,0,1
4,800,no_hashtag,0.062500,if you dotish to blight your car go right ahea...,0,0
...,...,...,...,...,...,...
1518,3728,no_hashtag,0.125000,nothing to fear its all about taking risk,1,0
1519,1657,no_hashtag,0.371429,and he almost collapsed bc he said his wish ca...,0,0
1520,6367,no_hashtag,0.914286,username it might have come out only too burst...,1,1
1521,1670,no_hashtag,0.088235,its always super awkward when world collide,0,0
1522,2839,no_hashtag,0.722222,philippine must protect internally displaced p...,1,1

In [122]:
error_test[error_test['target'] != error_test[0]]

,index,hashtags,keyword_target,cleaned_text,target,0
3,6362,no_hashtag,0.914286,if you ever think you running out of choice in...,0,1
6,1833,no_hashtag,0.617647,thief broke front window of hicksville store s...,0,1
21,6592,no_hashtag,0.700000,haley lu richardson fight for water in the las...,0,1
22,4585,no_hashtag,0.272727,carterville high school coach prepare for game...,1,0
28,3169,no_hashtag,0.600000,printable emergency plan template,0,1
...,...,...,...,...,...,...
1503,6615,Newsarama,0.705882,omega men writer explores terrorism religion i...,0,1
1504,3212,hiring Nursing Houston,0.333333,were click to apply rn ii emergency service ft...,1,0
1508,2488,no_hashtag,0.241379,i totally agree they rape kill destroy and lea...,1,0
1515,7175,OTRAMETLIFE,0.291667,this is a one direction concert not a war zone...,1,0
1518,3728,no_hashtag,0.125000,nothing to fear its all about taking risk,1,0